title: First Year BIS One-Stop
email: "© INL370 group 2"
# description:  "Welcome to the 'One-Stop Information Hub' for 1st Year Information Science Students! Our user-friendly website provides essential resources to navigate your program effectively, including course requirements, academic tools, on-campus support, and career opportunities. Join us on your journey to excel academically and thrive in the dynamic field of Information Science. Your success is our priority!"
baseurl: /INL370
url: http://nxthan.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed
